# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-01 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_auto_20190630_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='rango.Category'),
        ),
    ]
